
# [
#    "stylelint-config-standard",
#    "stylelint-config-prettier",
#    "stylelint-prettier/recommended",
#    # mapAsMap: true,
# ]
{
  "extends": "stylelint-config-standard",
  "stylelint-config-prettier",
   "stylelint-prettier/recommended",
  "rules": {
    "alpha-value-notation": "number",
    "selector-class-pattern": null
  }
}
# module.exports = {
#   extends: ["stylelint-config-standard",
#             "stylelint-config-prettier",
#             "stylelint-prettier/recommended"],
#   plugins: ["stylelint-order", "stylelint-scss"],
#   rules: {
#     "alpha-value-notation": "number",
#     "selector-class-pattern": null
#   }
